[package]
name = "lazorkit-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
borsh = "1.5"
pinocchio = { version = "0.9" }
no-padding = { path = "../no-padding", version = "0.1" }

[lints]
workspace = true
