[package]
name = "lazorkit-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey = { workspace = true }
pinocchio-system = { workspace = true }
no-padding = { workspace = true }
assertions = { workspace = true }

[dev-dependencies]
solana-program-test = "2.1"
solana-sdk = "2.1"
