[package]
name = "lazorkit-v2"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Lazorkit V2 smart wallet program"
publish = false
authors.workspace = true

[lints]
workspace = true

[dependencies]
pinocchio-pubkey = { version = "0.3" }
pinocchio = { version = "0.9" }
pinocchio-system = { version = "0.3" }
pinocchio-token = { version = "0.3" }
shank = { version = "0.4.2", git = "https://github.com/anagrambuild/shank.git" }
lazorkit-v2-state = { path = "../state" }
lazorkit-v2-instructions = { path = "../instructions" }
lazorkit-v2-assertions = { path = "../assertions" }
num_enum = "0.7.3"
bytemuck = { version = "1.13.1", features = ["derive"] }
no-padding = { path = "../no-padding" }
solana-security-txt = "=1.1.1"
default-env = "=0.1.1"
solana-program = "=2.2.1"
getrandom = { version = "0.2", features = ["custom"] }

[features]
test-bpf = []
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
rand = "0.8"
litesvm = { version = "0.6.1" }
test-log = "0.2.16"
anyhow = "1.0.71"
ecdsa = "0.16.9"
solana-clock = "=2.2.1"
bincode = "=1.3.3"
solana-client = "=2.2.1"
once_cell = "1.21.3"
spl-memo = "=6.0.0"
solana-secp256r1-program = "2.2.1"
openssl = { version = "0.10.72", features = ["vendored"] }
hex = "0.4.3"
